### ISSUE TITLE
does it support sveltekit?

### ISSUE THREAD

**Issue by sunw31** [NishuGoel/svelte-i18next#7]

**Comment by binajmen** [comment]
Hi @NishuGoel, I have the same question than @sunw31 :)

Are there guidelines when working with SvelteKit and SSR in general?

**Comment by codenius** [comment]
SvelteKit is out of beta now and released a stable version recently. Because of its benefits in navigation it's used by many people in combination with Svelte. Therefor I want to ask for SvelteKit support of this package again, because it would increase the benefit for many users.

**Comment by ricardo-rp** [comment]
I think a more specific set of feature requests would be helpful. What features do you expect from a sveltekit integration that the basic integration does not provide?

**Comment by ehsanonline** [comment]
no it doesn't.

**Comment by codenius** [comment]
> I think a more specific set of feature requests would be helpful. What features do you expect from a sveltekit integration that the basic integration does not provide?

It's more about general compatibility. In the moment the package is misconfigured and throws errors when running with SvelteKit. Check out [https://github.com/codenius/svelte-i18next](https://github.com/codenius/svelte-i18next) for a fixed version, that works with SvelteKit. I think after some testing it might be ready to merge.

**Comment by sapkra** [comment]
@codenius Thank you for addressing that issue. Is there any update on this?

@NishuGoel Would you merge and publish a new version if I create a PR for it?

**Comment by NishuGoel** [comment]
Yes ofcourse! Please go ahead
